version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typedoc
    versions:
    - 0.20.34
    - 0.20.35
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@azure/identity"
    versions:
    - 1.2.2
    - 1.2.3
    - 1.2.4
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: lint-staged
    versions:
    - 10.5.3
